use_frameworks!

target 'ScalingCarouselView_Example' do
  pod 'ScalingCarouselView', :path => '../'

  target 'ScalingCarouselView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase', :git => 'https://github.com/facebook/ios-snapshot-test-case', :branch => 'swift-beta-3'
    pod 'Nimble-Snapshots'
  end
end

# Disable bitcode in every sub-target and set Swift version
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
