use_frameworks!

target 'ScalingCarouselView_Example' do
  pod 'ScalingCarouselView', :path => '../'

  target 'ScalingCarouselView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
